### ISSUE TITLE
CSS3边框

### ISSUE THREAD

**Issue by ReZhangxin** [ReZhangxin/CSS3#1]
## box-shadow

只给box上面设置阴影
```css
.top{box-shadow: 0 -2px 2px rgba(0,0,0,.5);
```
只给box左面面设置阴影
```css
.top{box-shadow: -2px 0  0 rgba(0,0,0,.5);
```
box-shadow四边
```css
.box
{
     box-shadow: -5px 0 5px red,
          0 5px 5px aqua,
          5px 0 5px yellow,
          0 -5px 5px orange;
}
```
![box-shadow](http://ovmq7cupa.bkt.clouddn.com/box-shadow-min.png)
