### ISSUE TITLE
文本溢出

### ISSUE THREAD

**Issue by ReZhangxin** [ReZhangxin/CSS3#2]
属性 | 功能 | 取值
--- | --- | --- |
world-spacing | 词与词之间的间距 | normal(默认值),length(距离值，可负数)
letter-spacing | 字符之间的间距 | normal(默认值),length(距离值，可负数)
text-transform | 文本大小写 | uppercase(大写),lowercase(小写),**capitalize(首字母大写)**
white-space | 文字与文本之间的空白符 | nowrap(不换行)
text-overflow | 溢出文本显示 | ellipsis (文本溢出时用 `...` 表示)

### 单行文本超出用`...`显示

```css
element
{
  width:100px;
  text-overflow:ellipsis;
  white-space:nowrap;
  overflow:hidden;
}
```

### 多行文本溢出

```css
/*移动端和WebKit浏览器*/
element
{
  overflow : hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}

/*兼容*/
element
{
    position: relative;
    line-height: 1.4em;
    /* 4 times the line-height to show 4 lines */
    height: 5.6em;
}
element:after 
{
    content: "...";
    position: absolute;
    bottom: 0;
    right: 0;
    padding: 0 20px 1px 45px;
}
```
